# Generated by Django 5.2.6 on 2025-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_img_url_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
